namespace: devopsarr
name: radarr
# Version will be updated by workflow
version: 0.0.1
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: "Ansible collection for Radarr"
license_file: LICENSE
tags:
  - radarr
  - arr
  - series
repository: https://github.com/devopsarr/ansible-collection-radarr
#documentation: https://github.com/ansible-collection-migration/devopsarr.radarr/tree/main/docs
homepage: https://github.com/devopsarr/ansible-collection-radarr
issues: https://github.com/devopsarr/ansible-collection-radarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml